 pipeline {
   agent any
    parameters {
		string(description: 'ScriptfileName', name: 'ScriptfileName')
    }
    stages {
			stage('Executing the script in develop') {
                 when {
                   branch 'develop'
               }
               steps {
                script {
                  		sh """                                           

                                aws configure set default.region us-east-1

                                ls -lrt ${workspace}

                                aws s3 cp --recursive --sse AES256 ${workspace} s3://chiran
                               """
                        }

	       }
			}	
    }	
	}
